server:
  port: 8082

spring:
  application:
    name: ms-documento

  data:
    mongodb:
      uri: mongodb://localhost:27017/ms_documento

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost