server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**

        - id: ms-usuario
          uri: lb://ms-usuario
          predicates:
            - Path=/usuarios/**
          filters:
            - AuthFilter

        - id: ms-documento
          uri: lb://ms-documento
          predicates:
            - Path=/documentos/**
          filters:
            - AuthFilter

        - id: ms-tramite
          uri: lb://ms-tramite
          predicates:
            - Path=/tramites/**
          filters:
            - AuthFilter

        - id: ms-notificacion
          uri: lb://ms-notificacion
          predicates:
            - Path=/notificaciones/**
          filters:
            - AuthFilter

        - id: ms-storage
          uri: lb://ms-storage
          predicates:
            - Path=/storage/**
          filters:
            - AuthFilter

        - id: ms-auditoria
          uri: lb://ms-auditoria
          predicates:
            - Path=/auditoria/**
          filters:
            - AuthFilter



