server:
  port: 8084

spring:
  application:
    name: ms-oficina

  datasource:
    url: jdbc:postgresql://localhost:5432/ms_oficina
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html