server:
  port: 8090

spring:
  application:
    name: ms-registry-server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.eureka: OFF
eureka.server.enableSelfPreservation: false